### ISSUE TITLE
[Anti-adblock] socialgirls.im

### ISSUE THREAD

**Issue by bats0ft** [NanoAdblocker/NanoFilters#410]
**URLs where this issue occurs (Required)**
socialgirls.im

**### Describe the issue (Optional if obvious)**
The website will constantly reload itself every 5 seconds when adblock is enabled.
When adblock is disabled, the reloading stops. Suspect there is a script that causes the constant reloading.

**#### Environment (Required)**

- Operating System and Version: Windows 7
- Browser and Version: Chrome 77.0.3865.120 and Firefox Quantum 69.0.3
- Nano Adblocker Version: 1.0.0.127
- Nano Defender Version (Optional if you are not using it): 15.0.0.167

**#### Your filter lists (Required)**
Using default settings

**Comment by mapx-** [comment]
fixed

**Comment by bats0ft** [comment]
> 
> 
> fixed

it is not fixed.

**Comment by llacb47** [comment]
Purge your filters.

**Comment by mapx-** [comment]
Did you update the list ? Did you even try the filters from the commit above ?

**Comment by bats0ft** [comment]
> 
> 
> fixed

Still experience th

> 
> 
> Did you update the list ? Did you even try the filters from the commit above ?

My bad, first day here, missed out the commit. Confirmed issue resolved after adding filters in the commit. Thanks alot!

**Comment by jspenguin2017** [comment]
Ops, wrong button.
