### ISSUE TITLE
[Anti-adblock] upzone.cc

### ISSUE THREAD

**Issue by Majkovsky** [NanoAdblocker/NanoFilters#424]
https://ekino-tv.pl/serie/watch/kuchenne-rewolucje+season[20]+episode[11]+

"**Please disable your ad block extension to browse this site.**"

Nano Defender **15.0.0.170**
Mozilla Firefox **70.0.1**

**Comment by mapx-** [comment]
fixed

**Comment by Majkovsky** [comment]
> 
> 
> fixed

Not work, still problem

**Comment by Majkovsky** [comment]
![obraz](https://user-images.githubusercontent.com/31217689/69055668-a0b11080-0a0e-11ea-9f9d-c3406cb1b562.png)

**Comment by mapx-** [comment]
Did you update uBo filters list ?
Did you check in the logger if the filters are there ?

Try updating again perhaps you didn't get the last changes

**Comment by Majkovsky** [comment]
I updated the filters in uBlock Origin, entering the above web address still does not play the movie.

> ! https://github.com/uBlockOrigin/uAssets/issues/6588
*.gif$domain=cartoonth12.com,image
@@||jwpcdn.com/player/$script,domain=player.cartoonth12.com
*.mp4$media,redirect=noopmp3-0.1s,domain=cartoonth12.com

! https://github.com/NanoAdblocker/NanoFilters/issues/424
upzone.cc##+js(acis, Math, zfgloaded)
upzone.cc##+js(acis, document.getElementById, undefined)

>

**Comment by mapx-** [comment]
Tested again, FF + uBo + default settings + the filters added above + 2 polish lists, all fine here
If you are using some other blocking extension / addon disable it

**Comment by Majkovsky** [comment]
Adguard has prevented uBlock Origin from working properly. Regards, everything works

**Comment by mapx-** [comment]
yep ... use only 1 adblocker
